### ISSUE TITLE
Actualizar Tramos Renta Costa Rica 2024

### ISSUE THREAD

**Issue by AlftioH** [arturocr/arturocampos.dev#39]
Saludos @arturocr ,

Tu herramienta es magnífca.

Amablemente te agradezco poder actualizar los tramos de renta para este 2024

Hasta 929000	0%
Sobre el excedente de ₡929,000.00 hasta ₡1,363,000.00	10%
Sobre el excedente de ₡1,363,000.00 hasta ₡2,392,000.00	15%
Sobre el excedente de ₡2,392,000.00 hasta ₡4,783,000.00	20%
Sobre el excedente de ₡4,845,000.00	25%

Muchas gracias. 🤘💂

**Comment by AlftioH** [comment]
Muchas gracias  @arturocr 🦸🏻

**Comment by Sleepful** [comment]
mae! Buenísima la herramienta, muchas gracias 🤗 

Esos tractos reducidos tho... 😶
